spring.application.name=Lavacao

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/CardosoLavacao?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Opcional ? mostrar SQL no console
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true